
export const actionConstraint={
    GET_DATA_REQUEST:"GET_DATA_REQUEST",
    GET_DATA_FAILURE:"GET_DATA_FAILURE",
    GET_DATA_SUCCESS:"GET_DATA_SUCCESS",
    SORT_PRICE_LOW:"SORT_PRICE_LOW",
    SORT_PRICE_HIGH:"SORT_PRICE_HIGH"
}