export const actionType={
    STORE_PRODUCT_REMOVE_SUCCESS:"STORE_PRODUCT_REMOVE_SUCCESS",
    STORE_PRODUCT_REMOVE_REQUEST:"STORE_PRODUCT_REMOVE_REQUEST",
    STORE_PRODUCT_REMOVE_ERROR:"STORE_PRODUCT_REMOVE_ERROR",
    STORE_PRODUCT_GET_SUCCESS:"STORE_PRODUCT_GET_SUCCESS",
    STORE_PRODUCT_GET_REQUEST:"STORE_PRODUCT_GET_REQUEST",
    STORE_PRODUCT_GET_ERROR:"STORE_PRODUCT_GET_ERROR"
    
}